name: Reusable vulnerability scan workflow
permissions:
  actions: read
  issues: read
  security-events: read

on:
  workflow_call:
    inputs:
      website-url:
        required: true
        type: string
jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.17

      - name: Nuclei - DAST Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: ${{ inputs.website-url }}
          user-agent: "User-Agent:'Post build GitHub Actions Nuclei scan'"

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: nuclei.sarif
